language: java
jdk: openjdk8


install:
  - mvn dependency:go-offline
  - mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-compiler-plugin:3.5 -Dartifact=org.apache.maven.plugins:maven-enforcer-plugin:1.4.1

# codecov
before_script:
  - pip install --user codecov

# build
script: 
  - mvn clean install -Dsnapshot.version=-`git rev-parse --short HEAD`

after_success:
 - test $TRAVIS_BRANCH = "master" && mvn source:jar deploy --settings .travis/maven-settings.xml -Dmaven.test.skip=true
 - codecov
# - bash -x -e .travis/deploy.sh


#notifications:
#  irc:
#  - irc.freenode.org#pircbotx
